export DOTFILES="$HOME/.dotfiles"

function antibody-reload() {
    antibody bundle < $DOTFILES/zsh/zsh_plugins > $HOME/.zsh_plugins.sh
}

fpath+=~/.zfunc

export ZSH_AUTOSUGGEST_USE_ASYNC=true
export _ZL_DATA=~/.z
source ~/.zsh_plugins.sh

zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle :compinstall filename '/Users/lye/.zshrc'

autoload -Uz url-quote-magic bracketed-paste-magic
zle -N self-insert url-quote-magic
zle -N bracketed-paste bracketed-paste-magic

autoload -Uz compinit
compinit -i

# Enable Ctrl-x-e to edit command line
autoload -Uz edit-command-line
# Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

export PURE_CMD_MAX_EXEC_TIME=10

alias ll="exa -l"
alias la="exa -a"
alias ls="exa"

alias vi="nvim"

source $DOTFILES/zsh/git-aliases.zsh

HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data

export PATH="$PATH:$HOME/.emacs.d/bin"
